"""Per-project webhook secrets, generated by the engine when a project
is enabled and its hook is auto-registered. Gitea verifies them as an
HMAC signature (X-Gitea-Signature), GitLab as a plain token header
(X-Gitlab-Token)."""

from __future__ import annotations

import secrets
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    import asyncpg


class WebhookSecrets:
    """Implements the webhook router's SecretStore protocol for one forge."""

    def __init__(self, pool: asyncpg.Pool, forge: str | None = None) -> None:
        self.pool = pool
        # Only lookups by forge repo id need the forge scope; rotation
        # and creation are keyed by project id.
        self.forge = forge

    async def secret_for_repo(self, forge_repo_id: str) -> str | None:
        if self.forge is None:
            msg = "secret_for_repo needs a forge-scoped store"
            raise RuntimeError(msg)
        return await self.pool.fetchval(
            """
            SELECT s.secret FROM webhook_secrets s
            JOIN projects p ON p.id = s.project_id
            WHERE p.forge = $1 AND p.forge_repo_id = $2
            """,
            self.forge,
            forge_repo_id,
        )

    async def get_or_create(self, project_id: int) -> str:
        secret = await self.pool.fetchval(
            "SELECT secret FROM webhook_secrets WHERE project_id = $1",
            project_id,
        )
        if secret is not None:
            return secret
        secret = secrets.token_hex(32)
        # Concurrent creation: first writer wins.
        return await self.pool.fetchval(
            """
            INSERT INTO webhook_secrets (project_id, secret)
            VALUES ($1, $2)
            ON CONFLICT (project_id) DO UPDATE SET secret = webhook_secrets.secret
            RETURNING secret
            """,
            project_id,
            secret,
        )

    async def rotate(self, project_id: int) -> str:
        """Replace the secret; the old one stops verifying immediately.
        Auto-managed hooks re-sync on the next discovery cycle."""
        secret = secrets.token_hex(32)
        return await self.pool.fetchval(
            """
            INSERT INTO webhook_secrets (project_id, secret)
            VALUES ($1, $2)
            ON CONFLICT (project_id) DO UPDATE SET secret = EXCLUDED.secret
            RETURNING secret
            """,
            project_id,
            secret,
        )
