-- Per-repository Gitea webhook secrets, generated by the engine when a
-- project is enabled and the hook is auto-registered.

CREATE TABLE gitea_webhook_secrets (
    project_id BIGINT PRIMARY KEY REFERENCES projects (id) ON DELETE CASCADE,
    secret TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
